version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Debug info
          command: |
            npm --version
            node --version
            npx --version

      - run:
          name: Run tests
          command: |
            npm run coverage
      - run:
          name: Upload coverage reports
          command: |
            npm i codecov
            npx nyc report --reporter=lcov > coverage.lcov && codecov
